### ISSUE TITLE
Serverside rendering approach

### ISSUE THREAD

**Issue by ericjuta** [dminkovsky/radium-loader#1]
I was curious on your thoughts if this was plausible.

**Comment by dminkovsky** [comment]
Hi @rej156. I've never done server side rendering but I think it would be pretty simple to load the text of a css file and transform it to a Radium object using [css-to-radium](https://github.com/FormidableLabs/css-to-radium). Just [import the library](https://github.com/dminkovsky/radium-loader/blob/master/index.js#L1) and then [use it ](https://github.com/dminkovsky/radium-loader/blob/master/index.js#L10) on your CSS string.

**Comment by dminkovsky** [comment]
Closing this issue but feel free to comment here!
