### ISSUE TITLE
Example usage with LESS or SASS in the webpack pipeline?

### ISSUE THREAD

**Issue by austinmao** [dminkovsky/radium-loader#3]
Do you have an example on how to use this with webpack and in a file?
I am using .less files from a downloaded them. I have my less loader configured like so:

```
      { test: /\.less$/, loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!less?outputStyle=expanded&sourceMap' },
```

**Comment by dminkovsky** [comment]
Hmm that should work assuming the sass/less loader outputs CSS. Have you tried?

**Comment by austinmao** [comment]
I apologize for not responding. I have tried and it did not work.
